server:
  port: 8764
spring:
  application:
    name: service-item
    zipkin:
      base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
